services:
  app:
    environment:
      IS_CONTAINER: true
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_RUNTIME_DIR: /tmp
      PULSE_SERVER: $PLUSE_SERVER
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XDG_RUNTIME_DIR}/wayland-0
        target: /tmp/wayland-0

