# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  app:
    environment:
      IS_CONTAINER: true
      DISPLAY: $DISPLAY
      XDG_RUNTIME_DIR: /tmp
      GH_CONFIG_DIR: /home/appuser/.gh-config
      GH_BROWSER: /home/appuser/.local/bin/open
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      ZHISTFILE: /home/appuser/.zsh/history
      APP_USER_LOGIN_SHELL: /usr/bin/zsh
      SHELL: /usr/bin/zsh # SHELL変数はデフォルトでは設定されていない。ここで指定することでdevcontainerの中でtoggletermのデフォルトシェルとしてzshが起動する

    volumes:
      - type: bind
        source: ${HOME}/.config/gh
        target: /home/appuser/.gh-config
      - type: bind
        source: ${HOME}/dotfiles/files/.config/intelephense
        target: /home/appuser/intelephense
      - type: bind
        source: ${HOME}/.devcontainer_history
        target: /home/appuser/.zsh
      - type: bind
        source: ${HOME}/.aws
        target: /home/appuser/.aws
      - type: bind
        source: ${XDG_RUNTIME_DIR}/browser-pipe
        target: /tmp/browser-pipe
