# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  container:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IS_CONTAINER: true
      INTELEPHENSE_LICENCE_KEY: $INTELEPHENSE_LICENCE_KEY
      GH_CONFIG_DIR: /home/appuser/.gh-config
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_RUNTIME_DIR: /tmp
      PULSE_SERVER: $PLUSE_SERVER
      BROWSER: wslview
    volumes:
      - type: bind
        source: .
        target: /home/appuser/dotfiles
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XDG_RUNTIME_DIR}/wayland-0
        target: /tmp/wayland-0
      - type: bind
        source: ${HOME}/.config/gh
        target: /home/appuser/.gh-config
      - type: bind
        source: /usr/bin/wslview
        target: /usr/bin/wslview
    tty: true
