require("base")
require("plugins")
require("colorscheme")
require("_toggleterm")
require("_telescope")
require("keymap")
require("lspsetting")
require("git-settings")
require("clipboard")
require("_nvim-tree")
require("options")

