# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "<C-c>"
    context: "files"
    command: 'git commit -m "$(echo {{.Form.Row}} | cut -d" " -f1) {{.Form.Message}}"'
    prompts:
      - type: "input"
        title: "Select gitmoji"
        key: "Row"
        suggestions:
          command: 'cat "$XDG_DATA_HOME/git/emoji.json" | jq -r ".gitmojis[] | [.code,.name,.description] | @tsv" | sed "s/[\t\(\)]/ /g" | emojify'
      - type: "input"
        title: "Commit message"
        key: "Message"
  - key: "p"
    context: "localBranches"
    command: 'git pull --rebase'
  - key: "<C-l>"
    context: "global"
    command: "gh auth switch 2>&1 | awk '{print $NF}' > $HOME/.local/state/gh/active-user"
  - key: "<C-c>"
    context: "localBranches"
    command: "gh pr create --title '{{.Form.Title}}' --body ''"
    prompts:
      - type: "input"
        title: "Select commit message"
        key: "Title"
        suggestions:
          command: 'git log "$(gh pr view --json baseRefName | jq -r .baseRefName)..HEAD" --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" | grep -o "[a-f0-9]\{7\}" | xargs -I{} git --no-pager log -1 {} --format="%s"'
  - key: "<C-v>"
    context: "localBranches"
    command: "gh pr view --web"
