shell = 'zsh'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.compinit]
inline = '''
autoload -Uz compinit
compinit
'''

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

# see: https://github.com/zsh-users/zsh-autosuggestions#disabling-automatic-widget-re-binding
[plugins.zsh-autosuggestions.hooks]
pre = 'ZSH_AUTOSUGGEST_MANUAL_REBIND=1'
post = '''
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(accept-line-with-expand-alias history-beginning-search-backward-end history-beginning-search-forward-end)
'''
