format = """
$directory \
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 0
format = "[$path](bold yellow)[$read_only](bold red)"
read_only = " [READ_ONLY]"

[cmd_duration]
format = "[took](yellow) [$duration](yellow)"

[character]
success_symbol = "[\\$](bold black)"
error_symbol = "[\\$](bold red)"

format = "[$output]($style) [in](bold black)"
style = "bold purple"
