require("extensions/ui/colorscheme")
require("extensions/ui/toggleterm")
require("extensions/ui/telescope")
require("extensions/ui/nvim_tree")
require("extensions/ui/bufferline")
require("extensions/ui/hlslens")
require("extensions/ui/nvim_colorizer")
require("extensions/ui/which_key")
require("extensions/ui/incline")
require("extensions/ui/git_blame")
require("extensions/ui/lualine")

require("extensions/coding/gitsigns")
require("extensions/coding/code_runner")
require("extensions/coding/trim")
require("extensions/coding/nvim_surround")
require("extensions/coding/treesj")
require("extensions/coding/close_buffers")

require("extensions/lsp/lsp_setting")
require("extensions/lsp/linter")
require("extensions/lsp/formatter")
require("extensions/lsp/lspsaga")
