require("extensions/ui/colorscheme")
require("extensions/ui/toggleterm")
require("extensions/ui/telescope")
require("extensions/ui/nvim_tree")
require("extensions/ui/indent_blankline")
require("extensions/ui/lualine")
require("extensions/ui/bufferline")
require("extensions/ui/hlslens")
require("extensions/ui/noice")
require("extensions/ui/nvim_colorizer")
require("extensions/ui/which_key")
require("extensions/ui/incline")

require("extensions/coding/gitsigns")
require("extensions/coding/code_runner")
require("extensions/coding/trim")
require("extensions/coding/nvim_treesitter")
require("extensions/coding/nvim_surround")
require("extensions/coding/treesj")

require("extensions/lsp/lsp_setting")
require("extensions/lsp/linter")
require("extensions/lsp/formatter")
require("extensions/lsp/eslint")
require("extensions/lsp/lspsaga")
