-- require("noice").setup({
--     popupmenu = {
--         backend = "cmp",
--     },
--     lsp = {
--         progress = {
--             enabled = false,
--         },
--     },
--     messages = {
--         enabled = false,
--     },
-- })
