name: CI

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo curl
      - name: Install dotfiles
        run: ./.bin/install.sh
